### PR TITLE
Update brocaar/lorawan to 4b356a0 to incorporate v1.1rb for AU (fixes #719)

### LINKED ISSUE #719: Go get fails
Hi,

When I use `go get` to retrieve or update this repository I get an error:
```
$ go get github.com/TheThingsNetwork/ttn
# github.com/TheThingsNetwork/ttn/vendor/github.com/brocaar/lorawan/band
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:10:45: undefined: Band
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:11:23: undefined: MaxPayloadSize
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:14:22: undefined: MaxPayloadSize
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:33:22: undefined: MaxPayloadSize
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:53:10: undefined: Band
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:229:28: undefined: Channel
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:237:31: undefined: Channel
ttn/vendor/github.com/brocaar/lorawan/band/band_au915_928.go:245:30: undefined: Channel
```

I see why this error is generated, the included vendor is incomplete. I've also seen that this file differs from the file from the original vendor.

This is very odd from a programmers perspective. Why is the file there? Why is it different than the original repository? If it needs to be different, why isn't it backported to the original repository?

### PR DESCRIPTION
**Pull request by rikvdh**
See #719

### CODE REVIEW

**Comment by htdvisser** [comment]
The reason we had `lorawan/band` tagged at `a64aca28516d1024d898a412b2657b35b3539329` were the breaking changes introduced in https://github.com/brocaar/lorawan/commit/aa09ef2fd7be6786b853675bb208c26ceeaf9bfd. The changes in this PR result in those breaking changes being applied, which you can see happening in the Travis build. I pushed 36761935d1867ce2cd70a80ceef197a124e2d276 which includes the complete lorawan vendor, instead of only the one Go file (which was causing those errors).
